[project]
name = "esg-profile"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "prakgov-win", email = "prakirthgovardhanam@gmail.com" }
]
requires-python = ">=3.13"
dependencies = []

[project.scripts]
esg-profile = "esg_profile:main"

[build-system]
requires = ["uv_build>=0.12.19,<0.13.0"]
build-backend = "uv_build"
